# Theme
title: 君の名は
#Navigation
Menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

#Post date format
date_format: YY年MM月DD日
#Read more
read_more:  阅读更多
#Plugins setting
highlight:
  enable: true
  theme: atom-one-dark #reference: source => plugins => highlight => styles=> style name
# https://busuanzi.ibruce.info/
busuanzi:
  enable: true